language: ruby
cache: bundler
rvm:
  - 2.0.0
env:
  - DB=sqlite
# before_script:
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - rake cucumber
bundler_args: --binstubs=./bundler_stubs
