#language: ruby
#rvm:
  #- 2.0.0
#before_script:
  #- RAILS_ENV=test bundle exec rake db:create
  #- "bundle exec rails server -p 5000 &"
  #- "sleep 5" # Wait for the server to start up"
#script: bundle exec rake travis

language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - rake cucumber
bundler_args: --binstubs=./bundler_stubs
